# le-staging.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: ariemethacc@gmail.com
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Add a single challenge solver, HTTP01 using traefik (or nginx if you prefer)
    solvers:
      - http01:
          ingress:
            class: traefik
