image:
  tag: 2.3.3

deployment:
  enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

experimental:
  plugins:
    enabled: true
    
persistence:
  enabled: false
  storageClass: openebs-jiva-default

logs:
  general: 
    level: INFO
  access:
    enabled: true

ports:
  web:
    redirectTo: websecure
