---
# tasks file for configure-passwordless-ssh
# Variable setup.
- name: Include variables.
  include_vars: "main.yml"
- name: Include sensitive variables.
  include_vars: "vault.yml"

- name: Check if keyfile already exists
  stat:
    path: "{{ key_file }}"
  register: op

- name: Generating ssh key pair
  command: ssh-keygen -t ed25519 -b 4096 -f "{{ key_file }}" -q -N "{{ passphrase }}"
  when: op.stat.exists == false

- debug: 
    msg: "Key pair already exists. Using the same key."
  when: op.stat.exists

- name: Copy public key to the nodes
  command: sshpass -p "{{ root_password }}" ssh-copy-id -i "{{ key_file }}" "{{ root_user }}"@"{{ hostvars[item].ansible_host }}" -f -o StrictHostKeyChecking=no
  with_items:
    - "{{ groups['multi'] }}"


