apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: growingsewfast-com
  namespace: growingsewfast
spec:
  secretName: growingsewfast-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: growingsewfast.com
  dnsNames:
  - growingsewfast.com
