---
- name: Update all systems
  hosts: all

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
  tasks:
    - name: Update system
      apt:
        upgrade: dist
        update_cache: yes
      become: true
